latchset/kryoptic

src/ecc.rs
src/fips.rs
src/lib.rs
src/ossl/ecc.rs
src/ossl/rsa.rs
src/tests.rs
src/token.rs

Various improvements on the ECC code.

Ecc improvements

---

.github/workflows/build.yml
.github/workflows/format.yml
Makefile
build.rs
src/fips.rs
src/ossl/aes.rs
src/ossl/ecc.rs
src/tests.rs

Fix CI and add codespell checks

---

src/object.rs

Import from wrapped is handled a data buffer containing the raw unwrapped secret key.
Ensure this data is zeroized whether the object is successfuly imported (in which case a copy of the data buffer will have been made) or the operation fails.

Zeroize unwrapped key buffer

---

src/attribute.rs
src/lib.rs
src/ossl/aes.rs
src/ossl/rsa.rs

Avoid lots of open coded convrsions and use a safer method to clone a pointer into an onwed vector.
Also remove from_raw_parts() call whre possible, replacing with safer and/or better alternatives.

Add macro to deal with unsafe ptr to Vec

---

src/tests.rs
src/token.rs

Expose Token flags with PIN statuses

---

src/ossl/aes.rs

aes: verify the CCM parameters are consistent for wrapping

---

src/lib.rs
src/mechanism.rs
src/ossl/aes.rs
src/ossl/rsa.rs
src/tests/aes.rs
src/tests/attrs.rs
src/tests/ecc.rs
src/tests/hashes.rs
src/tests/kdf_vectors.rs
src/tests/keys.rs
src/tests/objects.rs
src/tests/rsa.rs
src/tests/session.rs
src/tests/signatures.rs
src/tests/util.rs

Use helpers to minimize the size of the tests, and mak them easier to read.

Refactor some more tests

---

src/aes.rs
src/ecc.rs
src/kdf.rs
src/object.rs
src/rsa.rs
src/tests/keys.rs
src/tests/util.rs

Adds a helper to set some common default values.
Add test infrastructure to test arbitrary attributes in objects.
Fixes #56

Implement common function to set default key object values

---

src/ossl/ecc.rs
src/tests/ecdh.rs

The spec says it is just a may, but better allow it than not given there has been confusion about this on the past and pkcs11-provider tries to pass in a DER encoded point.
Fixes #66

Accept DER encoded public keys

---

Cargo.toml
src/attribute.rs
src/fips/indicators.rs
src/fips/mod.rs
src/ossl.rs
src/ossl/aes.rs
src/ossl/common.rs
src/ossl/ecc.rs
src/ossl/eddsa.rs
src/ossl/hkdf.rs
src/ossl/hmac.rs
src/ossl/kbkdf.rs
src/ossl/pbkdf2.rs
src/ossl/rsa.rs
src/ossl/sshkdf.rs
src/tests/eddsa.rs
src/tests/mod.rs
src/tlskdf.rs

Some more fixes/optimizations for the CkAttrs struct
Change OsslParam to be more efficient like CkAttrs.

More safety for FFI array structures

---

src/object.rs

Some of the common key attributes were not stored unless explicitly specified in the template. We should always store the default values because applications are allowed to query those attributes at any time and we need to be able to return them when they do.
Found by using pkcs11-tool --list-objects which would spit a lot of errors about unavailable attributes.

Ensure default values are always stored

---

src/token.rs

Not ideal, but otherwise the token is just too slow
Fixes #85

Reduce the number of pbkdf2 rounds

---

Cargo.toml
src/aes.rs
src/ecc.rs
src/fips/indicators.rs
src/hash.rs
src/hkdf.rs
src/hmac.rs
src/lib.rs
src/mechanism.rs
src/ossl/aes.rs
src/ossl/aes_mac.rs
src/ossl/common.rs
src/ossl/ecc.rs
src/ossl/eddsa.rs
src/ossl/hash.rs
src/ossl/hmac.rs
src/ossl/rsa.rs
src/session.rs
src/sp800_108.rs
src/sshkdf.rs
src/tests/aes.rs
src/tests/util.rs
src/tlskdf.rs

Wire in more FIPS indicators.
Bubble up indicators from OpenSSL AES Cipher and Mac functions

More FIPS indicators

---

src/hkdf.rs
src/ossl/hkdf.rs

Found some minor issues while testing a new way to call HKDF from pkcs11-provider

HKDF Fixes

---

.github/workflows/build.yml
Cargo.toml
build.rs
src/enabled.rs
src/fips/mod.rs
src/hash.rs
src/hmac.rs
src/kasn1.rs
src/lib.rs
src/misc.rs
src/native/mod.rs
src/object.rs
src/ossl/fips.rs
src/ossl/mod.rs
src/tests/kdfs.rs
src/tests/keys.rs
src/tests/mod.rs
src/tests/objects.rs
src/tests/signatures.rs
src/token.rs

This change allows us to select which mechanisms to build in and allows for a relatively easy way to add or remove mechanisms in custom builds.

Initial support for selecting individual mechs to be built in

---

Cargo.toml
src/ec/ecdsa.rs
src/ec/mod.rs
src/enabled.rs
src/fips/indicators.rs
src/kasn1/mod.rs
src/kasn1/oid.rs
src/kasn1/pkcs.rs
src/kasn1/pyca/oid.rs
src/kasn1/pyca/pkcs.rs
src/ossl/common.rs
src/ossl/ecdh.rs
src/ossl/ecdsa.rs
src/ossl/eddsa.rs
src/ossl/montgomery.rs
src/rsa.rs
src/tests/ecdh_vectors.rs

Further simplify and consolidate code.
This PR is a dependency for #110 from which it was split off

More ASN.1/ECC refactoring

---

src/storage/format.rs

This unbreaks the pkcs11-provider CI and fetching certs in general.
Fixes #120

Fix fetching individual certificate attributes

---

src/storage/nssdb/mod.rs

This patch should unblock https://github.com/latchset/pkcs11-provider/pull/487

Properly set PIN initialization flag in NSSDB

---

src/ossl/aes.rs

The functions encrypt_initialize() and decrypt_initialize() have most of the duplicated code except for the OpenSSL function names. This unfifies the use on functions that work in both direction, keeping the code simpler and needing to fix bugs only in one place.
There were slight differences already in both of the implementations so I tried to take the better variant with more descriptive comments and checking.
Fixes: #145

aes: Unify encrypt/decrypt initialization

---

.github/codespell.sh
.github/workflows/rpm.yml
.gitignore
Cargo.toml
Makefile
build.rs
packaging/kryoptic.spec
packaging/rust2rpm.toml
src/ossl/fips.rs
src/ossl/mod.rs
src/pkcs11/interface.rs

I got few more comments in the Fedora review bug:
https://bugzilla.redhat.com/show_bug.cgi?id=2325933
It also integrates the RPM rebuild in CI, which we did not have

Another round of spec file updates after review  + RPM rebuild in CI

---

Makefile

Some more make targets

---

src/lib.rs

In tests we call fn_initialize in every test, so we need to be careful to avoid lock inversion.
This is extremely unlikely to be a problem in real applications, because generally initializations happens only once when the token is first loaded, before any other operation is attempted.

Resolve deadlock in tests

---

src/object.rs
src/tests/attrs.rs
src/tests/keys.rs

objects: Do not return CKR_ATTRIBUTE_TYPE_INVALID for unavailable attributes

---

Cargo.toml
packaging/kryoptic.spec

Based on the comment in
https://bugzilla.redhat.com/show_bug.cgi?id=2325933#c22
~~- [ ] Test suite updated with functionality tests~~
~~- [ ] Test suite updated with negative tests~~
~~- [ ] Documentation was updated~~

Fix SPDX License tag in spec file

---

.github/workflows/rpm.yml
CHANGELOG.md
Cargo.toml
misc/release.sh
packaging/kryoptic.spec

Prepares the tree for Release 1.1.0
- ~[ ] Test suite updated with functionality tests~

Release 1.1

---

CHANGELOG.md
misc/release.sh

Missed a link at the bottom of the document
- ~[ ] Test suite updated with functionality tests~

Changelog 1.1 fix

---

README.md

Minor, non-substantial improvements to the README.md.

Minor, non-substantial improvements to the README.md.

---

src/ec/montgomery.rs
src/tests/ec_montgomery.rs

Resolve incorrect Key type specification as reported in #221 
Fixes #221

Fix Montgomery Key Generation

---

.github/workflows/openssl_versions.yml
.github/workflows/pkcs11-provider.yml
Cargo.toml
build.rs
src/enabled.rs

Check which version we are building against and error out if incompatible features are requested.
Add tests to build against specific upstream versions to ensure features are compatible.
Fixes #92 
Fixes #218

Support building on different OpenSSL versions

---

src/mldsa.rs
src/ossl/mldsa.rs
src/tests/mldsa.rs

Fix ML-DSA Keygen and tests basic use case

Fix ML-DSA Keygen

---

src/ossl/fips.rs
src/tests/login.rs

These issues were found while trying to build RPMs on arches not available for testing in our CI like s390x and aarch64

Arch-specific build fixes

---

src/lib.rs
src/token.rs

Fix initialization of info in uninitialized token

---

.github/workflows/rpm.yml
Cargo.toml
src/ossl/common.rs

Expands structures we do not need the paste crate anymore.

Stop using the paste crate

---

Cargo.toml

This increases the MSRV to 1.65.0, but otherwise contains no breaking changes, just additions and bugfixes. Since I don't see a MSRV documented I didn't add a changelog entry for this.

deps: bump asn1 to v0.21

---

src/ossl/ffdh.rs

In a CI test in an unrelated PR we got a failure where, the (secret_len - keylen) calculation resulted in a negative integer error. Rust caught this as an invalid operation for an unsigned integer and paniced.
This probably happened because openssl returns the maximum shared secret length when we query for allocating the buffer size, but the actual length of the computed shared secret may be slightly shorter based on what the actual secret and public key values end up being.
Ensure that we always have a secret_len result from a call to EVP_PKEY_derive that is usable (no smaller than the smaller key size for AES). And compute/validate keylen after we have the final computed secret_len value.
Finally, ensure we return exactly keylen bytes, regardless of the size of the "secret" buffer.

FFDH: Ensure secret_len is big enough

---

.github/workflows/rpm.yml
CHANGELOG.md
Cargo.toml
misc/release.sh
packaging/kryoptic.spec

Release 1.2

---

src/fips/indicators.rs

Keys may not have the ephemeral validation object on. In that case explicilty heck the key and act accordingly.
Also move some code in helper functions for better readability.
Fixes #279
There are no specific tests because #278 will introduce enough tests to ensure this works correctly

Fix is_approved() to properly check input keys

---

CHANGELOG.md
Cargo.toml
src/enabled.rs
src/fips/indicators.rs
src/native/mod.rs
src/native/simplekdf.rs
src/object.rs
src/simplekdf.rs
src/tests/mod.rs
src/tests/simplekdf.rs

https://docs.oasis-open.org/pkcs11/pkcs11-spec/v3.1/os/pkcs11-spec-v3.1-os.html#_Toc111203697
Fixes: #274

Implement simple KDFs

---

src/lib.rs
src/pkcs11/headers/3.2/pkcs11.h

Import a fix fro pkcs11-headers, we do not implement this function yet but we should have the right prototypes anyway.

Import fix for pkcs11 3.2 header

---

ossl/Cargo.toml

The ossl crate's description was previously inherited from the workspace, which is too generic.
This change provides a more specific description for the crate, making its purpose clearer on publishing platforms like crates.io. The new description clarifies that it provides bindings to modern OpenSSL 3+ EVP APIs.

Set specific description for ossl crate
