latchset/kryoptic

src/ecc.rs
src/rsa.rs

should be straight-forward. But might be open to some simplification by adding this in a loop ... WDYT?

Add SHA3 signature mechanisms for RSA and ECC

---

README.md
src/ecc.rs
src/kasn1.rs
src/ossl/ecc.rs
src/rsa.rs
src/tests.rs

Fixes also unwrapping for RSA keys, but we might need better solution.
I think the `DerEncBigUint` ensures the BN is unsigned and starts with zero byte, which is something we do not want when we import the BN as a modulus as you are using the modulus size to enforce the buffer size. Without stripping the null byte from the modulus, the operation requires 257 B buffer for signature and verification of this signature does not work.
The RSA wrapping is also using the `RSAPrivateKey` ASN1 directly, but from my reading of the PKCS#11 specification, we should use `PrivateKeyInfo`. This not obvious for RSA keys as everything needed is in the inner object, but EC keys needs the `privateKeyAlgorithm` field to learn what curve is used, if I read it right. 
Keeping it as a draft as there is more …

Support for wrapping EC keys + RSA wrapping fixes/comments/questions

---

src/ecc.rs
src/kasn1.rs
src/rsa.rs

~Using the `defined-by` magic.~
Using opaque OCTET STRING
Fixes #10.

Share the PrivateKeyInfo structure among RSA and ECC implementation

---

src/kasn1.rs
src/ossl/ecc.rs
src/ossl/rsa.rs
src/slot.rs
src/tests.rs
testdata/test_ecc_operations.json
testdata/test_sign_verify.json

This covers various corner cases of RSA PSS mechanisms and ECC keys found during running the p11test against the kryoptic (CI integration in progress).

Various fixes for RSA PSS and ECC

---

src/lib.rs
src/mechanism.rs
src/ossl/aes.rs
src/ossl/rsa.rs
src/tests.rs

The `aes` module did not implement the `encryption_len()` which caused every operation with NULL result querying for the result size to fail.
There are some attempts to implement this inside of the encrypt() function, which became pointless and could be deleted (all within `if cipher.is_null` block:
https://github.com/latchset/kryoptic/blob/1c13e98edc766584281ac3dff7664b40a0afda35/src/ossl/aes.rs#L841-L851
But these are now used by wrapping, which does not have this handling separately and which I properly did not review yet so feel free to wait before merging this to figure out wrapping.

Fix AES `C_Encrypt` with NULL result to query result size

---

.github/workflows/build.yml
.gitignore
Cargo.toml
Makefile
README.md
src/lib.rs
src/object.rs
src/slot.rs
src/storage.rs
src/storage/json.rs
src/storage/memory.rs
src/storage/sqlite.rs
src/tests.rs
src/token.rs
testdata/test_aes_operations.json
testdata/test_basic.json

Refactor storage to allow multiple backends.
Add a sqlite based storage backend (see more info on the commit).
Rework some PIN operations to simplify and address storage/masking issues.
also
Fixes #23

Storage changes

---

src/attribute.rs
src/storage/sqlite.rs

This allows us to be:
a) more portable files
b) stricter in validating data
c) support Null values which are needed in some rare case to indicate the attribute is present but empty (ulValueLen = 0).
Fixes #20

Use stricter data conversion to store data in sql

---

src/object.rs
src/tests.rs

The code was simply doing the wrong thing,
correctly use the template to generate the object and then add the CKA_VALUE attribute to it.
Fixes #30

Fix Key unwrap

---

src/lib.rs
src/tests.rs

This is rough PoC of allowing the kryoptic to work without the pReserved pointer and without the init args altogether (as they are not mandatory). The code can probably be simplified, but this worked for me and allowed me to run the general pkcs11 applications against kryoptic without issues.

Support configuration through environment variable

---

src/ossl/aes.rs
src/ossl/common.rs
src/ossl/rsa.rs
src/tests.rs

* The OsslParams construction was ignoring some values, which caused all RSA keys generated were always default 2k
* The CCM wrapping output length was dependent on the DataLen parameter, which is not really available for the caller at the time of calculation so changing to the length of provided data allows the caller to set the parameter to reasonable value for final operation to actually work
* Fix the expected lenght calculation for `AES_CBC_PAD` mechanism.
With these changes, the current set of tests in OpenSSL `p11test` works.

Fixes various corner cases of AES and RSA operations

---

.github/codespell.sh
src/aes.rs
src/hash.rs
src/hmac.rs
src/kdf.rs
src/lib.rs
src/mechanism.rs
src/object.rs
src/ossl/common.rs
src/ossl/pbkdf2.rs
src/pbkdf2.rs
src/tests/aes.rs
src/tests/kdfs.rs
src/tests/keys.rs
src/tests/util.rs

This is another "good one" where PKCS#11 spec deviates from what you would expect, and uses C_GenerateKey to implemnt Key derivation instead of C_DeriveKey.
This means we now need to pass mechanisms and object factories to the generate function because the template can specify any key type, so we need to get the generate_key function from the PBKDF mechanism, but we need to be able to find the crate() mechanism for any supported key type ...

Add PBKDF2 support

---

src/kdf.rs
src/ossl/aes.rs
src/ossl/rsa.rs
src/tests/rsa.rs

My reading of the PKCS#11 specs is that the RSA-OAEP parameters source needs to be `CKZ_DATA_SPECIFIED` regardless if the lablel is specified or not. Currently, the combination of `source=CKZ_DATA_SPECIFIED` and NULL source data and `ulSourceDataLen=0` is crashing now.

RSA: Accept empty OAEP parameter label

---

src/lib.rs
src/storage.rs
src/storage/json.rs
src/storage/memory.rs
src/storage/sqlite.rs
src/token.rs

This caching layer was a premature optimization, and cause the interfaces to require mutability in places where it wasn't really warranted, and in the end many callers would end up calling .clone() anyway for various reasons.
Will follow up with other PRs later to further change this.

Remove caching layer from the storage interface

---

src/ecc.rs
src/error.rs
src/object.rs
src/ossl/aes.rs
src/ossl/common.rs
src/ossl/ecc.rs
src/ossl/hash.rs
src/ossl/hkdf.rs
src/ossl/hmac.rs
src/ossl/kdf.rs
src/ossl/pbkdf2.rs
src/ossl/rsa.rs
src/token.rs

Instead of exposing raw pointers which is quite unsafe, internalize as many unsafe operations as possible on these raw pointers so that the actual interface of these wrapped type is mostly safe.
Declare interfaces that still deal with raw pointers as unsafe so that proper care is done when handling them.
Fixes #63

Make OpenSSL context wrappers safer

---

src/tests/objects.rs
src/tests/util.rs
src/token.rs

Creating a session object only requires a writable session, not full login.
Fixes #68

Fix creation of session objects

---

src/lib.rs
src/object.rs
src/session.rs
src/tests/keys.rs
src/token.rs

When a private key has this attribute set to true it commands that any operation (decryption/signature/etc..) done with this key requires an extra authentication to authorize the individual operation.
This is done by setting flags on the session that will control proper authentication is checked if necessary, and support for the special CKU_CONTEXT_SPECIFIC user type into the fn_login() function.
Fixes #70

Add support for CKA_ALWAYS_AUTHENTICATE behavior

---

src/lib.rs
src/misc.rs
src/tests/keys.rs

Filters at operation init time and returns an error if the key indicated that it has a list of allowed mechanisms and the mechanism presented is not in the list.
A missing attribute is handled as if any mechanism is allowed.
Fixes #71

Implement support for CKA_ALLOWED_MECHANISMS

---

src/attribute.rs
src/eddsa.rs
src/hash.rs
src/lib.rs
src/misc.rs
src/ossl/ecc.rs
src/ossl/eddsa.rs
src/pbkdf2.rs
src/tlskdf.rs
src/token.rs

This code improves usage of CK_ATTRIBUTE arrays by creating a structure partially inspired by OsslParam, but using better methods to deal with lifetimes and avoiding copies where not needed.

Improve use of CK_ATTRIBUTE arrays

---

src/token.rs

The copy function is filling token info fixed size strings with spaces However we failed to catch the trailing null that apparently comes in a &str type, ending up with embedding an illegal null in these token info strings.

Do not embed nulls in token info

---

.github/workflows/build.yml
Cargo.toml
build.rs
fips.h
ossl.h

For non-FIPS builds we can link to the system libcrypto without issues, so add that as an option.

Add support for linking openssl dynamically

---

Cargo.toml

The 0.68 is no longer available in Fedora packages and I do not think there is a reason to stay behind (if it will generally work with newer version).
I am not sure if this is the best approach or we should make it dependent on wider range of versions (or if we should set up dependabot or something to keep the dependencies updated in the long term).

Bump bindgen to 0.69

---

build.rs
src/pkcs11/interface.rs

It turns out the bindgen assumes 64b architecture by default when converting constants, which causes warnings like
```
warning: literal out of range for `u32`
--> src/pkcs11/bindings.rs:7:50
|
7 | pub const CK_UNAVAILABLE_INFORMATION: CK_ULONG = 18446744073709551615;
|                                                  ^^^^^^^^^^^^^^^^^^^^
|
= note: the literal `18446744073709551615` does not fit into the type `u32` whose range is `0..=4294967295`
= note: `#[warn(overflowing_literals)]` on by default
```
but more important, most of the tests keep failing as the comparisons around this value wont work.
Rather than inventing a way to convert the constant to c-type ulong, I thought setting specific value known as to be the MAX would be more obvious.
Builds run in rawhide now: …

bindings: Create 32b compatible bindings

---

Cargo.toml
src/ec_montgomery.rs
src/ecc.rs
src/ecdh.rs
src/enabled.rs
src/ossl/ec_montgomery.rs
src/ossl/ecc.rs
src/ossl/ecdh.rs
src/ossl/mod.rs
src/tests/ec_montgomery.rs
src/tests/mod.rs

This refactors the ECDH out of the generic ECC module, as the same code is used also for derivation operation with Montgomery EC keys.

Add support for EC_MONTGOMERY keys

---

build.rs

Fixed following compilation error
root@evk:~/kryoptic# CONFDIR=/etc cargo build
Compiling kryoptic v0.1.0 (/root/kryoptic)
error: unsupported output in build script of `kryoptic v0.1.0 (/root/kryoptic)`: `cargo::rerun-if-changed=pkcs11_headers/3.1/pkcs11.h` Found a `cargo::key=value` build directive which is reserved for future use. Either change the directive to `cargo:key=value` syntax (note the single `:`) or upgrade your version of Rust. See https://doc.rust-lang.org/cargo/reference/build-scripts.html#outputs-of-the-build-script for more information about build script outputs.

build.rs: fix Cargo calls

---

src/storage/nssdb/mod.rs
src/tests/nssdb.rs

The fetch side was unconditionally applying sensitivity object parsing which meant it would try to decrypt any CKA_VALUE attribute regardless of object type. However the store() function would encrypt it only for the private database objects.
Fix the asymmetry and add a test to ensure writing public object works as expected.

Fix handing of public objects with nssdb

---

src/storage/nssdb/mod.rs

Enumerating all objects on the token leads to calling search on NSS DB without any search arguments, which resulted in invalid SQL queries. This allows me to move on a bit further with the testing of NSS DB

nssdb: Fix object search without template

---

src/storage/nssdb/config.rs
src/storage/nssdb/mod.rs
src/tests/nssdb.rs

Parsing of the NSS configuration string was working just for the first key=value and exploded for anything after that. This fixes couple issues found while parsing different key=value inputs, quoting. Most of the inputs are unused in the code so there is no way to test them for now.

Fix parsing NSSDB configuration

---

src/object.rs
src/storage/nssdb/mod.rs
src/tests/nssdb.rs

This is mostly my naive approach. Not sure if there is a better way or better place where this could be handled.

Fix deleting NSSDB objects

---

src/storage/nssdb/mod.rs
src/tests/nssdb.rs

Fixes up the dfb480a384be9762ef01487a355a80d9e47e2b55 which
started checking the certificate type on the certificates for
pulling default attributes that can not be stored in the NSS DB.

 nssdb: Add missing attrs for getting skipped attributes 

---

.github/workflows/build.yml
src/error.rs
src/storage/nssdb/ci.rs
src/storage/nssdb/mod.rs
src/tests/nssdb.rs

Adds a caching layer to NSSDB to reduce the performance impact of the key derivation operations.
NSSDB uses a particularly costly operation (pbkdf2) to derive a key for each of the attributes being encrypted.
This PR also adds a test to demonstrate the issue.
This test takes a relatively long time to execute without the cache:
```
$ time cargo test --features standard,nssdb test_nssdb_key_cache
Compiling kryoptic v0.1.0 (/home/remote/ssorce/devel/git/kryoptic)
Finished `test` profile [unoptimized + debuginfo] target(s) in 4.96s
Running unittests src/lib.rs (target/debug/deps/kryoptic_pkcs11-0639a8933718ff9b)
running 1 test
test tests::nssdb::test_nssdb_key_cache has been running for over 60 seconds
test tests::nssdb::test_nssdb_key_cache ... ok
test result: ok. 1 passed; 0 failed; 0 …
```

Add a caching layer for NSSDB per-attribute keys

---

Cargo.toml
src/aes.rs
src/attribute.rs
src/hmac.rs
src/kasn1/mod.rs
src/misc.rs
src/native/hmac.rs
src/object.rs
src/ossl/aes.rs
src/ossl/common.rs
src/ossl/ecdsa.rs
src/ossl/fips.rs
src/ossl/hmac.rs
src/ossl/rsa.rs
src/storage/aci.rs
src/storage/nssdb/ci.rs
src/storage/nssdb/mod.rs
src/tests/nssdb.rs

Using valgrind's callgrind tool I am analyzing the behavior of with the nssdb storage backend which shows particularly bad performance in pkcs11-provider's CI.
The first easy pick was to remove the Zeroize crate, which single-handedly accounted for a 50% of the time spent in pbkdf2 operations.
The second easy pick was to rewrite the HAM initialization to use fixed slices instead of vectors for the internal state.
The nssdb is still much slower than the others, due to higher use of the pbkdf2 function, yet nssdb uses the same and it is much faster.
Some playing around shows the "native" version is about 20/30 % slower than the OpenSSL one we use in fips mode ... but there is definitely more work to do to improve performance here.

More performance improvements with nssdb

---

src/fips/indicators.rs
src/lib.rs
src/ossl/aes.rs
src/ossl/hmac.rs
src/tests/aes.rs

There were several issues:
* The `check_mac_fips_indicators()` won't do anything for the CMACs, as the cmac implementation in FIPS provider does not implement the fips indicator OSSL_PARAM.
* The AES key with SIGN/VERIFY flags was also not marked correctly as FIPS valid so any CMAC operation on that given key caused the FIPS indicator failure.
* Adding explicit tag/mac length checks for CMAC and GCM
* Ignoring CCM and KMAC as I think we do not certify these
I am still not sure about the GCM as the specs are vague. Putting 64b for now.

Improve output length checking for FIPS indicators in AES/HMAC code

---

src/storage/nssdb/mod.rs
src/storage/sqlite.rs
src/storage/sqlite_common.rs

In many distributions this seem to be on by default already, although the official sqlite documentations ays it is off by default.
Also by experimentation it seem this setting is not saved to the db file, so ensure secure_delete is turned on whenever we open the database.

Add pragma to ensure secure delete is on

---

src/fips/indicators.rs
src/lib.rs
src/storage/nssdb/attrs.rs
src/storage/nssdb/mod.rs
src/tests/keys.rs
src/tests/rsa.rs

C_GenerateKeyPair / C_WrapKey / C_UnWrapKey were missing invocations to fips indicators checks.
Added checks and added tests to ensure they work

Add missing FIPS checks for Key creation functions

---

.github/workflows/pkcs11-provider.yml

This inspects the pkcs11 provider keeps working with kryoptic, which is mostly symmetric to the kryoptic test in the pkcs11-provider repo in:
https://github.com/latchset/pkcs11-provider/blob/main/.github/workflows/kryoptic.yml

Add integration test with pkcs11-provider

---

src/ossl/rsa.rs
src/storage/nssdb/attrs.rs
src/tests/rsa.rs
testdata/test_rsa_operations.json

Currently, `ALLOWED_MECHANISMS` were tested only with AES keys. This add test with RSA keys to make sure they are effective also with different key types.

Increase test coverage of ALLOWED_MECHANISMS usage

---

src/ossl/aes.rs
src/tests/aes.rs

Found while messing with some openssl test code and pkcs11-provider

Padding bug mismatch

---

src/fips/indicators.rs
src/hmac.rs
src/tests/tls.rs
src/tlskdf.rs

Second version does only the TLS PRF test with @simo5's suggested approach, that will invoke dynamically (and only once using the Lazy construct), as well as for the `CKM_TLS_MAC` mechanisms, that internally use TLS PRF.

Add TLS PRF selftests in FIPS mode

---

src/ossl/common.rs
src/ossl/ecdsa.rs
src/ossl/rsa.rs

These were found while working on pkcs11-provider's address sanitizer tests.

Fix memory leaks in unsafe code

---

.gitignore
Makefile
build.rs

As we have to use OUT_DIR, there is no simple way to index the generated files as they are stored in a location that changes freuently due to the hash in the target directory.
At build time store the file names of the generate files so that if the file is present they can be indexed.

Silly way to generate cscope database

---

.github/workflows/build.yml

Sounds like the latest fedora changed the location of metadata and package downloads.

ci: Cache DNF downloads

---

src/lib.rs
src/tests/attrs.rs
src/tests/login.rs

> If this function is successful and it closes the last session between
> the application and the token, the login state of the token for
> the application returns to public sessions. Any new sessions to the token
> opened by the application will be either R/O Public or R/W Public sessions.
https://docs.oasis-open.org/pkcs11/pkcs11-spec/v3.1/os/pkcs11-spec-v3.1-os.html#_Toc111203273
Fixes: #163

Logout when last session is closed on given token

---

.github/workflows/build.yml
Cargo.toml
Makefile
README.md
src/lib.rs

The README.md was not updated when we last change defaults.
This commit restores the default build to point to the "standard" feature. This makes it slightly harder to build non standard configurations, but makes it easier for new-comers.
Fixes #162

Change default feature

---

src/aes.rs
src/ec/ecdh.rs
src/hash.rs
src/hkdf.rs
src/lib.rs
src/mechanism.rs
src/native/hmac.rs
src/session.rs
src/sp800_108.rs
src/sshkdf.rs
src/storage/aci.rs
src/tests/session.rs
src/tlskdf.rs

Also refactors how operations are handled to fix #168

Reduce the number of unimplemnetd functions

---

src/error.rs
src/lib.rs
src/session.rs
src/tests/combined.rs
src/tests/mod.rs

The code for this functions was all already available, just a matter of wiring up the calls.
Implements digest/encrypt, decrypt/digest, sign/encrypt, decrypt/verify.

Combined functions support

---

src/lib.rs
src/object.rs
src/ossl/aes.rs
src/ossl/hkdf.rs
src/storage/aci.rs
src/storage/sqlite.rs
src/storage/sqlite_common.rs
src/tests/token.rs
src/token.rs

The migration tool automatically changed some of thcode causing some churn. I manually changed some of the things, like removing expr_2021 from macros as it was not necessary and changing the renaming of the now reserved word gen from r#gen to generator.
A bunch of let Some() {} else () expressions were changed to matches, I let that be, sometime smatch turns out to be idiomatic, sometimes it is about the same readability.

Switch to 2024 edition

---

src/attribute.rs
src/object.rs
src/storage/sqlite.rs
src/tests/keys.rs

Turned out the START_DATE and END_DATE attributes had default value defined, but the flag was missing, which lead to not storing the default attributes in DB.
Throughout the chain of storing and reading DATE type, there were several checks for valid dates (which empty string is not) so there were some changes needed to loosen these checks.
Fixes: #182
- [~] This is not a code change

Fix storing and reading default DATE attributes

---

src/lib.rs
src/ossl/aes.rs

Fixes: #170
If you think some more tests will be needed, please let me know. I think we support this only for AES-GCM/CCM for now.
- ~[ ] Test suite updated with functionality tests~
- ~[ ] This is not a code change~

Introduce CKF_MULTI_MESSAGE flag

---

src/session.rs
src/tests/session.rs

Fixes #191 
- ~[ ] This is not a code change~

Fix incorrect error returned on un-initialized operations

---

src/tests/signatures.rs
testdata/test_sign_verify_rsa.json

Use SHA256 so that we avoid failures in downstream tests where SHA1 signatures are disabled in openssl.
Fixes RPM test that dynamically links Fedora rawhide's openssl which currently has SHA1 signatures hard-disabled.

Replace SHA1 test signature

---

.gitmodules
Cargo.toml
Makefile
build.rs
fips.h
src/ossl/aes.rs
src/ossl/fips.rs
src/ossl/hkdf.rs
src/ossl/hmac.rs
src/ossl/kbkdf.rs
src/ossl/sshkdf.rs
src/tests/aes.rs
src/tests/rsa.rs
src/tests/signatures.rs
src/tests/util.rs

Rebases the openssl submodule from a version based on Openssl 3.2 to a pre-release of the code that will go in Openssl 3.5.0 with additional patches from Red Hat for fips compliance nd sha1 hardening.
The fips indicator stuff had to be overhauled.
Note:
Two test do not correctly report unapproved fips indicators and will need more investigation.
It may be due to incomplete patching on the openssl side wrt indicators we used to check previously. Keeping PR as draft until openssl branches upstream and thse two test are investigated.

Rebase openssl submodule to 3.5 (prerelease)

---

src/object.rs
src/tests/aes.rs
src/tests/ec_montgomery.rs
src/tests/ecdh.rs
src/tests/ecdh_vectors.rs
src/tests/kdf_vectors.rs
src/tests/kdfs.rs
src/tests/keys.rs
src/tests/mlkem.rs
src/tests/tls.rs

The spec says:
"If the CKA_SENSITIVE attribute is CK_TRUE, or if the CKA_EXTRACTABLE attribute is CK_FALSE, then certain attributes of the private key cannot be revealed in plaintext"
However the code was performing a logical "and" instead of an "or". Correct the code and the tests to properly check/set the CKA_SENSITIVE value.
- ~[ ] This is not a code change~
- ~[ ] Any issues marked for closing are fully addressed~
- ~[ ] This feature/change has adequate documentation added~
- ~[ ] A changelog entry is added if the change is significant~

Fix check for object sensitivity as per spec

---

src/lib.rs
src/tests/hashes.rs

Currently, only the generic secret keys were allowed to be digested. This allows also AES keys (as I did not find any limitation specified in specs) and adds test coverage as there was really none for this code path.

Allow digesting AES keys and add test coverage.

---

src/ossl/ecdh.rs
src/tests/ecdh.rs

For some reason, I set the output length to the 2 * field sizes initially. This does not have any effect on deriving AES keys as they can not be that large, but this could explode for secret keys that could get larger.

ecdh: Fix max ECDH output size

---

src/lib.rs
src/ossl/aes.rs
src/ossl/rsa.rs
src/tests/aes.rs
src/tests/keys.rs
src/tests/rsa.rs
testdata/test_rsa_operations.json

Fixes `C_WrapKey` size queries that previously crashed kryoptic (#184). 
This is a naive approach, which involves creating 0-length buffer for the size query, doing the export of the key and if the buffer is not large enough, returning.
Better approach would be to store the intermediate state of the operation and continue from there once we will have large enough buffer, but it would involve much more changes.

Fix C_WrapKey size query

---

src/mechanism.rs
src/tests/ecdh.rs

* The ECDH test had needless slicing as discussed in #203. Removed
* The ECDH test had also needless check of lengths before comparing buffers
* The warnings when built without PQC started to annoy me so I fixed them :)
- ~[ ] Test suite updated with functionality tests~
- ~[ ] Any issues marked for closing are fully addressed~
- ~[ ] There is a test suite reasonably covering new functionality or modifications~
- ~[ ] This feature/change has adequate documentation added~
- ~[ ] A changelog entry is added if the change is significant~

Minor cleanups in tests and rust warning fixes

---

.github/workflows/migrate.yml
.github/workflows/rpm.yml
Cargo.toml
packaging/kryoptic.spec
src/tools/softhsm/test.sh
src/tools/softhsm/test_init.rs
src/tools/softhsm/test_signature.rs

The Fedora 42 splits opensc to libs and tools, but only libs are
multilib. This means the 64b pkcs11-tool can not work with the 32b
kryoptic in the tests.
This is attempt to get rid of the opensc dependency by using the
rust-cryptoki API in the migrate test.

tests: Drop pkcs11-tool dependency of migrate test

---

Cargo.toml

The bindgen was updated in rawhide to 0.71
~- [ ] Test suite updated with functionality tests~

Bump bindgen dependency version to follow rawhide

---

CHANGELOG.md
src/attribute.rs
src/storage/json_objects.rs
src/storage/nssdb/mod.rs
src/storage/sqlite.rs
testdata/test_rsa_operations.json

Some attributes are actually well defined arrays of other attributes.
The two array types are arrays of CK_ULONGs and arrays of CK_ATTRIBUTEs
The latter is used for "TEMPLATE" attributes.
This PR implements support for more correctly storing and parsing arrays of CK_ULONG attributes.
At the same time we prevent trying to store TEMPLATE attributes.
This is because it is not entirely clear how to deal with the memory pointers referenced by the CK_ATTRIBUTE structure, and currently storing these attributes simply results in a broken attribute referencing arbitrary memory.
Fixes #217

Add better support for array of attributes

---

README.md

To use a static build of OpenSSL, it is not enough to set KRYOPTIC_OPENSSL_SOURCES, the `dynamic` feature also needs to be disabled.
Mention this in `README.md` and provide an example.

Improve documentation for using a static build of OpenSSL.

---

src/config.rs

`sql` is not a known DB type.  The correct type is `sqlite`.
Thanks to Jakub Jelen <jjelen@redhat.com> for help debugging this.

Fix example configuration file.

---

Cargo.toml
src/fips/indicators.rs
src/ossl/mldsa.rs

Add more mechanisms to FIPs indicators and ensure the underlying openssl operations are checked for indicators in multi-part operations.

Update some FIPS indicators

---

README.md
build.rs
src/config.rs
src/fips/mod.rs
src/lib.rs
src/slot.rs
src/tests/mod.rs
src/tests/nssdb.rs

Add the ability to set a series of env vars at build time to control the FIPS token name/version/build info
Additionally make FIPS tunables per token instead of being global
Fixes #240

Change some build time variables and configs

---

CHANGELOG.md
src/ec/ecdsa.rs
src/ec/eddsa.rs
src/ec/mod.rs
src/ec/montgomery.rs
src/kasn1/pkcs.rs
src/tests/keys.rs

Edwards and Montgomery keys were lacking encoding/decoding functions for import/export
Add missing code by creating common handlers and test key generating and wrapping/unwrapping for all there key types

Add Key wrapping support and tests for all EC keys

---

src/config.rs
src/lib.rs

Adds missing doc strings for globals
Depends on #242

More doc strings

---

.github/workflows/build.yml
.github/workflows/openssl_versions.yml
src/lib.rs
testdata/test.conf

This worked for me, but:
* I did not add a reproducer yet -- not sure if there is a good way to do that except for introducing some bash script that would run `cargo test`
* I am not much happy to have the `#[cfg(test))` throughout the code as this means the we can not test the code in the `#[cfg(not(test))]` branch.
So opening as a draft.
Fixes: #226

tests: Avoid failures when configuration file is present in default path

---

Cargo.toml

The cryptoki was updated in Fedora to 0.9.0 so follow the suit here to keep the Fedora RPM builds working.
https://src.fedoraproject.org/rpms/rust-cryptoki/pull-request/2
~- [ ] Test suite updated with functionality tests~
~- [ ] Rustdoc string were added or updated~
~- [ ] CHANGELOG and/or other documentation added or updated~

Cargo: Bump cryptoki version to match version in Fedora

---

src/ossl/aes.rs
src/tests/aes.rs

The buffer length checks in the `src/ossl/aes.rs` `encrypt_update` and `decrypt_update` functions, for the `AES_ECB`, `AES_CBC` and `AES_CBC_PAD` mechanisms, had an off-by-one error that caused failures in the `OpenJDK` `PKCS11` test suite.

Fix buffer length check in AES update functions

---

src/fips/indicators.rs
src/lib.rs
src/native/tlskdf.rs
src/tests/tls.rs
src/tlskdf.rs

Implementation of `CKM_TLS12_EXTENDED_MASTER_KEY_DERIVE` derive mechanism.
WIP as I need to find some test vectors (was not successful yet).

Implement TLS 1.2 EMS derive

---

src/fips/indicators.rs
src/native/simplekdf.rs
src/tests/simplekdf.rs
src/tests/tls.rs
src/tests/util.rs

Allows to check that input keys in KDFs that are passed via parameters are fips compliant.
Note that even though the bug mentions HKDF, in that case the input key is used as salt and the code there (in openssl) already checks that the salt length complies with FIPS requirements where needed, so the key must not be checked for fips approval in that case as the salt length may have separate requirements.
Fixes #280

Add fips checks for KDFs additional input keys

---

.github/workflows/openjdk-integration.yml

Add a `GitHub Actions` reusable workflow to run `OpenJDK` `PKCS11` tests against `libkryoptic_pkcs11.so` built in the `Build` workflow.
Start with a single test, `Cipher/EncryptionPadding.java` that currently fails but will pass once some other issues are fixed; specifically: the 1) how to run `hmacify.sh` (suspected cause of current panic during `OpenSSL` provider initialization) and 2) how to configure key sensitivity.

Add OpenJDK continuous integration

---

src/fips/indicators.rs

On i686 the value 0xffffffff is the maximum value that a CK_ULONG can carry, which causes an overflow when we use ($val + 7 )/ 8 to convert bits to bytes.
Given that it is never reasonable to have keys that are gigabits long anyway let's clam the max down to 16M bits (2MiB) for now.

Reduce max key sizes to avoid overflow

---

.github/workflows/openjdk-integration.yml

Run `openjdk-integration.yml` regardless of outcome of `build.yml`, and on push and pull request events.
This change makes `openjdk-integration.yml` run on `push` and `pull_request` events (like `build.yml`), regardless of whether `build.yml` succeeds.
I kept `workflow_dispatch` so I have a button to run the job in case I want to change the `jdk21u-dev` repository.

openjdk-integration.yml: Run on pull_request and push

---

ossl/src/cipher.rs
ossl/src/lib.rs
ossl/src/mac.rs
ossl/src/pkey.rs
src/ossl/aes.rs
src/ossl/ecdsa.rs
src/ossl/eddsa.rs
src/ossl/ffdh.rs
src/ossl/hmac.rs
src/ossl/mldsa.rs
src/ossl/mlkem.rs
src/ossl/montgomery.rs
src/ossl/rsa.rs

Add `Drop` implementations for the `EccData`, `FfdhData`, `MlkeyData`, and `RsaData` structs.
These implementations use `OPENSSL_cleanse` to securely zero out sensitive key material (private keys, seeds, RSA components) when the structs go out of scope. This prevents key data from lingering in memory, reducing the risk of exposure.
Fixes #295

Implement Drop to cleanse sensitive key data

---

ossl/src/asymcipher.rs
ossl/src/cipher.rs
ossl/src/derive.rs
ossl/src/digest.rs
ossl/src/lib.rs
ossl/src/mac.rs
ossl/src/pkey.rs
ossl/src/rand.rs
ossl/src/signature.rs
src/config.rs

I ported `sequoia-openpgp` from `rust-openssl` to (a slightly patched version of) `ossl`.  This is the first set of patches from that effort.  I picked them in the hope that they are uncontroversial, and we can get them out of the way.

Some `ossl` API work, mostly polishing

---

dummy.txt
ossl/dummy.txt
ossl/src/fips.rs

This is needed to deal with integrity checks during cargo tests, as they can't use the rodata method on test binaries.
This change drops the need for exaternal dummy.txt files and instead creates the check file on the fly at test time.

Minor rework of dummy integrity check

---

.github/workflows/openjdk-integration.yml
testdata/openjdk/jtreg-kryoptic.sh
testdata/openjdk/openjdk-jtreg-tests.txt
testdata/openjdk/p11-kryoptic-sensitive.txt
testdata/openjdk/p11-kryoptic.txt

Add `p11-kryoptic.txt` and `p11-kryoptic-sensitive.txt` `OpenJDK` configuration files and `openjdk-jtreg-tests.txt`, used by `jtreg-kryoptic.sh`.
Modify `openjdk-integration.yml` to accommodate default dependency locations expected by `jtreg-kryoptic.sh`.
Also change the set of tests to the subset of `PKCS11Test.java` tests that pass on my `CentOS` `9` `NSS` `FIPS` system, and that also pass on current `Kryoptic`.
`jtreg-kryoptic.sh` can now be run outside of the `.yml` file:
```
$ testdata/openjdk/jtreg-kryoptic.sh check-jtreg
```
I think it makes sense for this script and its associated configuration files to live in `Kryoptic`.  I can still maintain them via pull requests if the continuous integration job fails.  And I plan to add more test cases as they are made to work.

Add jtreg-kryoptic.sh OpenJDK test script

---

.github/workflows/rpm.yml
Cargo.toml
src/storage/nssdb/mod.rs

Just ignore the attributes we do not know anythign about.
This is causing a CKR_DEVICE_ERROR on unknown attributes (like CKA_PAREMETER_SET) instead of just returning they are unknown.

Do not fail fetches on unknown attributes

---

ossl/Cargo.toml
ossl/src/cipher.rs
ossl/src/lib.rs
ossl/src/pkey.rs

This patch series adds functionality required to port Sequoia PGP to ossl.  First, we add support for OCB, which is the MTI AEAD mode of RFC9580.  Second, we tweak ossl's notion of block size so that AEAD constructions are treated the same way as stream ciphers by `OsslCipher::buffer_size`, and we expose the block size as `OsslCipher::block_size`.  Third, we add some helper functions to load and store RSA keys using the OpenPGP wire format.

Add support for OCB, OsslCipher::block_size, and RSA helpers for implementations of RFC9580

---

.github/workflows/pkcs11-provider.yml
ossl/src/lib.rs

As pointed out in #311 we do not free the Context on drop.
When this code was embedded in kryoptic this was not really necessary as Kryoptic uses a single global context in a lazyly initialized static variable.
But now Ossl exposes the ability to create as many as you want, so they need to be freed on drop.

Ossl: Ensure libctx is freed on drop

---

ossl/src/asymcipher.rs
ossl/src/fips.rs
ossl/src/pkey.rs
ossl/src/signature.rs
src/attribute.rs
src/kasn1/mod.rs
src/object.rs
src/storage/nssdb/ci.rs
src/tests/attrs.rs
src/tests/token.rs

The never settable attribute was not handled and did allow changing attributes that were never settable (even the OBJECT_VALIDATION, even though it is ephemeral).
~~~~
Additionally the Rust was updated showing new warnings:
```
warning: hiding a lifetime that's elided elsewhere is confusing
--> ossl/src/asymcipher.rs:30:25
|
30 |     oaep_params: Option<&RsaOaepParams>,
|                         ^^^^^^^^^^^^^^ the lifetime is elided here
31 | ) -> Result<OsslParam, Error> {
|             --------- the same lifetime is hidden here
|
= help: the same lifetime is referred to in inconsistent ways, making the signature confusing
= note: `#[warn(mismatched_lifetime_syntaxes)]` on by default
help: use `'_` for type paths
|
31 | ) -> Result<OsslParam<'_>, Error> {
|                      ++++
``` …

Do not allow setting never-settable attributes (+avoid new warnings caused by new Rust version)

---

ossl/ossl.h
ossl/src/lib.rs

- Adds a way to load legacy providers for ossl bindings

Add function to load legacy provider

---

ossl/src/tests/mod.rs
src/lib.rs
src/native/simplekdf.rs
src/object.rs
src/tests/simplekdf.rs

Reported in parallaxsecond/rust-cryptoki#310 that the token objects do not behave as expected. After some investigation, I figured out I messed up the key creation there and attributes were off.
This attempts to fix it, but still the ALWAYS/NEVER attributes do not seem to be set to the right values and I am unable to figure out why. Any thoughts?
~- [ ] Rustdoc string were added or updated~

Fix Simple KDFs to work with token objects
